// src/faqData.js
const faqDatabase = [
  { keywords: ["what is","anderson wealth","about anderson","who are you","your company"], question: "What is Anderson Wealth Management?", answer: "Anderson Wealth Management is a financial planning and wealth-management firm based in Regina, Saskatchewan. We help individuals, families, and business owners make informed financial decisions and build long-term financial security." },
  { keywords: ["evan anderson","founder","advisor","who is evan","about evan"], question: "Who founded Anderson Wealth / who is the advisor?", answer: "Evan Anderson is the founder and advisor at Anderson Wealth Management. He focuses on building long-term relationships and helping clients achieve financial security." },
  { keywords: ["email","email address","contact email","how to email","e-mail","mail"], question: "How can I email Anderson Wealth?", answer: "You can email Evan Anderson at evan.anderson@andersonwealth.ca. For administrative matters, email admin@andersonwealth.ca." },
  { keywords: ["phone","call","telephone","contact number","phone number"], question: "What is your phone number?", answer: "You can call Anderson Wealth at +1 (306) 577-3384." },
  { keywords: ["hours","when are you open","business hours","schedule","opening hours"], question: "What are your office hours?", answer: "Office hours are Monday to Friday, 8:30 a.m. to 4:30 p.m." },
  { keywords: ["book","consultation","free consultation","appointment","meeting","schedule","book a consultation"], question: "How do I book a consultation?", answer: "You can book a free, no-obligation consultation using the 'Book A Free Consultation' button on the website or the booking page accessible from the main menu." },
  { keywords: ["services","what do you offer","products","what can you do","services list","offer","provide","solutions"], question: "What services do you offer?", answer: "Services include investment planning and insurance solutions: retirement analysis, registered and non-registered accounts, mutual funds, ETFs, HISAs, GICs, segregated funds, annuities, GIAs, life, disability & critical illness, key person insurance, asset protection, succession planning, and buy-sell agreement funding." },
  { keywords: ["insurance","life insurance","critical illness","disability","segregated funds","annuities","gias","asset protection"], question: "What insurance products do you provide?", answer: "Anderson Wealth provides insurance solutions such as life insurance, disability, critical illness coverage, key person insurance, asset protection strategies, segregated funds, annuities, and GIAs to protect families and businesses." },
  { keywords: ["investments","investment planning","mutual funds","tfsa","rrsp","gic","hisa","etf"], question: "What investment products are available?", answer: "Investment offerings include retirement analysis, investment planning, registered and non-registered accounts, mutual funds, ETFs, HISAs and GICs. The firm references mutual funds sold through Portfolio Strategies Corporation." },
  { keywords: ["process","how does it work","steps","planning process","discovery","implementation","maintenance"], question: "How does your planning process work?", answer: "The process follows four steps: 1) Discovery — learn about your goals and current situation; 2) Plan development — create a tailored plan; 3) Implementation — put the plan into action; 4) Maintenance — ongoing review and updates as life changes." },
  { keywords: ["how long","results","timeframe","when will i see results"], question: "How long until I see results from working with you?", answer: "Results vary by client and their risk profile, timeline and objectives. Many clients report a sense of clarity after the initial meeting; long-term financial results depend on the agreed plan and implementation." },
  { keywords: ["who will i work","team","advisor","staff","assistant"], question: "Who will I work with?", answer: "You will work directly with Evan Anderson, supported by licensed administrative staff. Contact emails for Evan and the admin team are provided on the site." },
  { keywords: ["location","where are you","address","office","regina","saskatchewan","based"], question: "Where are you located?", answer: "Anderson Wealth is based in Regina, Saskatchewan." },
  { keywords: ["remote","virtual","outside regina","other provinces","work remotely"], question: "Do you work with clients outside Regina?", answer: "Yes — Anderson Wealth can work with clients across Saskatchewan and in other provinces using secure virtual meetings, phone calls or email." },
  { keywords: ["cost","price","fees","how much","expensive","fee-based","commission"], question: "How much do your services cost?", answer: "Fees depend on the services provided. Some solutions are fee-based while others (for example insurance) may be commission-based. Fee structure and compensation are explained during the consultation." },
  { keywords: ["commission","fee-based","compensation","how are you paid"], question: "How are you compensated?", answer: "Compensation models vary: some investment services are fee-based and certain insurance products are commission-based. The firm is transparent about compensation during client conversations." },
  { keywords: ["tax","tax planning","taxes","tax efficient"], question: "Can you help with tax planning?", answer: "Yes. Anderson Wealth provides guidance on tax-efficient strategies and will coordinate with tax professionals when appropriate." },
  { keywords: ["estate","estate planning","will","inheritance"], question: "Can you help with estate planning?", answer: "Yes. The firm assists with estate planning considerations and can work with legal professionals to implement estate strategies that protect family wishes." },
  { keywords: ["risk","conservative","aggressive","moderate","risk level"], question: "What investment risk levels do you support?", answer: "They support conservative, moderate and aggressive risk profiles and tailor recommendations to each client's goals, timeline and comfort with risk." },
  { keywords: ["review","how often","annual review","frequency of review"], question: "How often will my plan be reviewed?", answer: "Plans are recommended to be reviewed at least annually, and can be updated more frequently if circumstances change." },
  { keywords: ["privacy","confidential","secure","private information"], question: "Is my information kept private?", answer: "Yes. Anderson Wealth follows privacy and security practices to protect client information; details are handled confidentially and used only to support planning." },
  { keywords: ["credentials","qualifications","licensed","certified","advisor qualifications"], question: "What credentials do your advisors have?", answer: "Advisors at Anderson Wealth are licensed to provide financial planning, investment and insurance services and complete ongoing education to remain compliant and current." },
  { keywords: ["first meeting","what to bring","prepare","initial consultation","documents"], question: "What should I bring to my first meeting?", answer: "Bring whatever financial information you have (income, savings, investments, insurance, debts and goals). If you don't have everything organized, the advisor will help you start the process." },
  { keywords: ["free","no obligation","first meeting free","consultation cost","free consultation"], question: "Is the first meeting free?", answer: "Yes — the initial consultation is free and without obligation. It is an opportunity to meet and determine if there is a good fit." },
  { keywords: ["portfolio strategies","partnership","mutual funds sold through","third party"], question: "Are mutual funds sold through a third party?", answer: "Yes — the website notes that mutual funds products are sold through Portfolio Strategies Corporation (stated in the website footer)." },
  { keywords: ["contact form","send message","contact us form","website form"], question: "Can I send a message through the website?", answer: "Yes — the Contact page includes a contact form where you can submit name, email, service interest (Insurance, Investing, Lending, or I'm not sure) and a message." },
  { keywords: ["faq insurance","how much life insurance","type of policy","critical illness why","why critical illness"], question: "How much life or critical illness insurance do I need?", answer: "Insurance needs depend on individual circumstances. Anderson Wealth evaluates debts, income needs and family situation to recommend term or permanent policies and to explain benefits of critical illness coverage." },
  { keywords: ["business owner","entrepreneur","small business","key person","buy-sell","succession"], question: "Can you help business owners?", answer: "Yes. Services for business owners include key person insurance, buy-sell agreement funding, succession planning and strategies to protect business value and owner families." },
  { keywords: ["help","need advisor","do i need help","why hire advisor"], question: "How do I know if I need a financial advisor?", answer: "If you are planning for retirement, buying a home, protecting your family, managing investments or running a business, a financial advisor can help by creating an actionable plan and offering ongoing support." },

  // Detailed Insurance Questions
  { keywords: ["insurance plans","what insurance","types of insurance","insurance coverage","protection plans"], question: "What insurance plans do you provide?", answer: "We provide comprehensive insurance solutions including Life Insurance, Disability Insurance, Critical Illness coverage, Key Person Insurance, Asset Protection, Retirement Protection, Succession Planning, Buy-Sell Agreement Funding, Segregated Funds, Annuities, and GIAs (Guaranteed Investment Accounts)." },
  { keywords: ["life insurance plan","whole life","term life","permanent life","life coverage"], question: "What types of life insurance are available?", answer: "We offer both term and permanent life insurance policies. Term provides coverage for a specific period, while permanent (whole life) provides lifetime coverage with potential cash value accumulation. We evaluate your debts, income needs, and family situation to recommend the best option for you." },
  { keywords: ["disability insurance","disability coverage","income protection","disability plan"], question: "What is disability insurance?", answer: "Disability insurance protects your income if you become unable to work due to illness or injury. This coverage ensures you can continue to meet your financial obligations and maintain your lifestyle even if you can't work." },
  { keywords: ["critical illness","critical illness insurance","illness coverage","serious illness"], question: "What does critical illness insurance cover?", answer: "Critical illness insurance provides a lump-sum payment if you are diagnosed with a serious illness such as cancer, heart attack, or stroke. This coverage helps pay for medical expenses, lost income, or other costs not covered by traditional health insurance." },
  { keywords: ["segregated funds","seg funds","segregated fund","what are seg funds"], question: "What are segregated funds?", answer: "Segregated funds are insurance-based investment products that combine growth potential with insurance protection. They offer creditor protection, potential death benefit guarantees, and maturity guarantees, making them ideal for protecting your investment while growing your wealth." },
  { keywords: ["annuities","annuity","retirement income","guaranteed income"], question: "What are annuities?", answer: "Annuities are insurance products that provide guaranteed income, typically for retirement. They convert a lump sum or series of payments into a steady stream of income, helping ensure you won't outlive your savings." },
  { keywords: ["gia","guaranteed investment account","gias","guaranteed investment"], question: "What are GIAs?", answer: "GIAs (Guaranteed Investment Accounts) are insurance-based savings products that offer guaranteed returns with principal protection. They provide a safe, predictable way to grow your money while being creditor-protected." },
  { keywords: ["key person insurance","key man","business insurance","key employee"], question: "What is key person insurance?", answer: "Key person insurance protects your business against the financial impact of losing a critical employee or owner. It provides funds to cover recruitment costs, lost revenue, or debt obligations if a key person becomes disabled or passes away." },
  { keywords: ["buy sell agreement","buy-sell","business succession","partner buyout"], question: "What is buy-sell agreement funding?", answer: "Buy-sell agreement funding uses life insurance to ensure business continuity. If a business partner passes away or becomes disabled, the insurance provides funds for the surviving partners to buy out their share, preventing financial strain and keeping the business running smoothly." },

  // Detailed Investment Questions
  { keywords: ["investment plans","investment products","what investments","invest money","investing options"], question: "What investment products do you offer?", answer: "We offer a comprehensive range of investment solutions including Retirement Analysis, Registered Accounts (RRSP, TFSA), Non-Registered Investment Accounts, Mutual Funds, ETFs (Exchange-Traded Funds), HISAs (High-Interest Savings Accounts), and GICs (Guaranteed Investment Certificates). Mutual funds are sold through Portfolio Strategies Corporation." },
  { keywords: ["rrsp","registered retirement","retirement savings plan","rrsp account"], question: "What is an RRSP?", answer: "An RRSP (Registered Retirement Savings Plan) is a tax-advantaged account for retirement savings. Contributions are tax-deductible, and investment growth is tax-deferred until withdrawal, typically in retirement when your tax rate may be lower." },
  { keywords: ["tfsa","tax free","tax-free savings","tfsa account"], question: "What is a TFSA?", answer: "A TFSA (Tax-Free Savings Account) is a registered account where investment growth and withdrawals are completely tax-free. It's a flexible savings tool that can be used for any goal—retirement, home purchase, emergency fund, or general savings." },
  { keywords: ["mutual funds","mutual fund","fund investment","managed funds"], question: "What are mutual funds?", answer: "Mutual funds pool money from many investors to purchase a diversified portfolio of stocks, bonds, or other securities. They're professionally managed and offer instant diversification, making them suitable for investors who want professional management without picking individual stocks. We offer mutual funds through Portfolio Strategies Corporation." },
  { keywords: ["etf","etfs","exchange traded","index fund"], question: "What are ETFs?", answer: "ETFs (Exchange-Traded Funds) are investment funds that trade on stock exchanges like individual stocks. They typically track an index and offer low fees, diversification, and flexibility. ETFs are ideal for cost-conscious investors seeking broad market exposure." },
  { keywords: ["gic","guaranteed investment certificate","gics","guaranteed return"], question: "What are GICs?", answer: "GICs (Guaranteed Investment Certificates) are low-risk investments that guarantee your principal and a fixed rate of return over a set term (typically 1-5 years). They're CDIC-insured and perfect for conservative investors or those saving for short-term goals." },
  { keywords: ["hisa","high interest savings","savings account","high interest"], question: "What are HISAs?", answer: "HISAs (High-Interest Savings Accounts) offer higher interest rates than regular savings accounts while keeping your money accessible. They're ideal for emergency funds or short-term savings where you need liquidity and safety." },
  { keywords: ["retirement analysis","retirement planning","retire","retirement strategy"], question: "What is retirement analysis?", answer: "Our retirement analysis is a comprehensive review of your current financial situation, projected retirement needs, and gap analysis. We create a customized strategy to help you achieve your retirement goals through the right mix of investments, savings vehicles, and income strategies." },
  { keywords: ["registered account","non registered","taxable account","investment account types"], question: "What's the difference between registered and non-registered accounts?", answer: "Registered accounts (like RRSP and TFSA) offer tax advantages but have contribution limits and rules. Non-registered accounts have no contribution limits but investment income is taxable. We help you determine the optimal mix based on your goals and tax situation." },

  // Ashley Healey
  { keywords: ["ashley","ashley healey","secretary","admin","licensed assistant","who is ashley"], question: "Who is Ashley Healey?", answer: "Ashley Healey is our Licensed Assistant at Anderson Wealth Management. Growing up in rural Saskatchewan, Ashley developed strong teamwork and community values through retail management. She joined the financial services industry in 2020, driven by a passion to empower clients with financial knowledge and confidence. You can reach Ashley at admin@andersonwealth.ca." },
  { keywords: ["contact ashley","reach ashley","email ashley","ashley email"], question: "How can I contact Ashley?", answer: "You can contact Ashley Healey, our Licensed Assistant, at admin@andersonwealth.ca for administrative matters, appointment scheduling, or general inquiries." },
  { keywords: ["who answers","admin contact","administrative help","office admin"], question: "Who handles administrative matters?", answer: "Ashley Healey, our Licensed Assistant, handles administrative matters including appointment scheduling, general inquiries, and client support. She joined our team in 2020 and is passionate about empowering clients with financial knowledge. Contact her at admin@andersonwealth.ca." }
];

export default faqDatabase;
