// src/faqData.js
const faqDatabase = [
  { keywords: ["what is","anderson wealth","about anderson","who are you","your company"], question: "What is Anderson Wealth Management?", answer: "Anderson Wealth Management is a financial planning and wealth-management firm based in Regina, Saskatchewan. We help individuals, families, and business owners make informed financial decisions and build long-term financial security." },
  { keywords: ["evan anderson","founder","advisor","who is evan","about evan"], question: "Who founded Anderson Wealth / who is the advisor?", answer: "Evan Anderson is the founder and advisor at Anderson Wealth Management. He focuses on building long-term relationships and helping clients achieve financial security." },
  { keywords: ["email","email address","contact email","how to email","e-mail","mail"], question: "How can I email Anderson Wealth?", answer: "You can email Evan Anderson at evan.anderson@andersonwealth.ca. For administrative matters, email admin@andersonwealth.ca." },
  { keywords: ["phone","call","telephone","contact number","phone number"], question: "What is your phone number?", answer: "You can call Anderson Wealth at +1 (306) 577-3384." },
  { keywords: ["hours","when are you open","business hours","schedule","opening hours"], question: "What are your office hours?", answer: "Office hours are Monday to Friday, 8:30 a.m. to 4:30 p.m." },
  { keywords: ["book","consultation","free consultation","appointment","meeting","schedule","book a consultation"], question: "How do I book a consultation?", answer: "You can book a free, no-obligation consultation using the 'Book A Free Consultation' button on the website or the booking page accessible from the main menu." },
  { keywords: ["services","what do you offer","products","what can you do","services list","offer","provide","solutions"], question: "What services do you offer?", answer: "Services include investment planning and insurance solutions: retirement analysis, registered and non-registered accounts, mutual funds, ETFs, HISAs, GICs, segregated funds, annuities, GIAs, life, disability & critical illness, key person insurance, asset protection, succession planning, and buy-sell agreement funding." },
  { keywords: ["insurance","life insurance","critical illness","disability","segregated funds","annuities","gias","asset protection"], question: "What insurance products do you provide?", answer: "Anderson Wealth provides insurance solutions such as life insurance, disability, critical illness coverage, key person insurance, asset protection strategies, segregated funds, annuities, and GIAs to protect families and businesses." },
  { keywords: ["investments","investment planning","mutual funds","tfsa","rrsp","gic","hisa","etf"], question: "What investment products are available?", answer: "Investment offerings include retirement analysis, investment planning, registered and non-registered accounts, mutual funds, ETFs, HISAs and GICs. The firm references mutual funds sold through Portfolio Strategies Corporation." },
  { keywords: ["process","how does it work","steps","planning process","discovery","implementation","maintenance"], question: "How does your planning process work?", answer: "The process follows four steps: 1) Discovery — learn about your goals and current situation; 2) Plan development — create a tailored plan; 3) Implementation — put the plan into action; 4) Maintenance — ongoing review and updates as life changes." },
  { keywords: ["how long","results","timeframe","when will i see results"], question: "How long until I see results from working with you?", answer: "Results vary by client and their risk profile, timeline and objectives. Many clients report a sense of clarity after the initial meeting; long-term financial results depend on the agreed plan and implementation." },
  { keywords: ["who will i work","team","advisor","staff","assistant"], question: "Who will I work with?", answer: "You will work directly with Evan Anderson, supported by licensed administrative staff. Contact emails for Evan and the admin team are provided on the site." },
  { keywords: ["location","where are you","address","office","regina","saskatchewan","based"], question: "Where are you located?", answer: "Anderson Wealth is based in Regina, Saskatchewan." },
  { keywords: ["remote","virtual","outside regina","other provinces","work remotely"], question: "Do you work with clients outside Regina?", answer: "Yes — Anderson Wealth can work with clients across Saskatchewan and in other provinces using secure virtual meetings, phone calls or email." },
  { keywords: ["cost","price","fees","how much","expensive","fee-based","commission"], question: "How much do your services cost?", answer: "Fees depend on the services provided. Some solutions are fee-based while others (for example insurance) may be commission-based. Fee structure and compensation are explained during the consultation." },
  { keywords: ["commission","fee-based","compensation","how are you paid"], question: "How are you compensated?", answer: "Compensation models vary: some investment services are fee-based and certain insurance products are commission-based. The firm is transparent about compensation during client conversations." },
  { keywords: ["tax","tax planning","taxes","tax efficient"], question: "Can you help with tax planning?", answer: "Yes. Anderson Wealth provides guidance on tax-efficient strategies and will coordinate with tax professionals when appropriate." },
  { keywords: ["estate","estate planning","will","inheritance"], question: "Can you help with estate planning?", answer: "Yes. The firm assists with estate planning considerations and can work with legal professionals to implement estate strategies that protect family wishes." },
  { keywords: ["risk","conservative","aggressive","moderate","risk level"], question: "What investment risk levels do you support?", answer: "They support conservative, moderate and aggressive risk profiles and tailor recommendations to each client's goals, timeline and comfort with risk." },
  { keywords: ["review","how often","annual review","frequency of review"], question: "How often will my plan be reviewed?", answer: "Plans are recommended to be reviewed at least annually, and can be updated more frequently if circumstances change." },
  { keywords: ["privacy","confidential","secure","private information"], question: "Is my information kept private?", answer: "Yes. Anderson Wealth follows privacy and security practices to protect client information; details are handled confidentially and used only to support planning." },
  { keywords: ["credentials","qualifications","licensed","certified","advisor qualifications"], question: "What credentials do your advisors have?", answer: "Advisors at Anderson Wealth are licensed to provide financial planning, investment and insurance services and complete ongoing education to remain compliant and current." },
  { keywords: ["first meeting","what to bring","prepare","initial consultation","documents"], question: "What should I bring to my first meeting?", answer: "Bring whatever financial information you have (income, savings, investments, insurance, debts and goals). If you don't have everything organized, the advisor will help you start the process." },
  { keywords: ["free","no obligation","first meeting free","consultation cost","free consultation"], question: "Is the first meeting free?", answer: "Yes — the initial consultation is free and without obligation. It is an opportunity to meet and determine if there is a good fit." },
  { keywords: ["portfolio strategies","partnership","mutual funds sold through","third party"], question: "Are mutual funds sold through a third party?", answer: "Yes — the website notes that mutual funds products are sold through Portfolio Strategies Corporation (stated in the website footer)." },
  { keywords: ["contact form","send message","contact us form","website form"], question: "Can I send a message through the website?", answer: "Yes — the Contact page includes a contact form where you can submit name, email, service interest (Insurance, Investing, Lending, or I'm not sure) and a message." },
  { keywords: ["faq insurance","how much life insurance","type of policy","critical illness why","why critical illness"], question: "How much life or critical illness insurance do I need?", answer: "Insurance needs depend on individual circumstances. Anderson Wealth evaluates debts, income needs and family situation to recommend term or permanent policies and to explain benefits of critical illness coverage." },
  { keywords: ["business owner","entrepreneur","small business","key person","buy-sell","succession"], question: "Can you help business owners?", answer: "Yes. Services for business owners include key person insurance, buy-sell agreement funding, succession planning and strategies to protect business value and owner families." },
  { keywords: ["help","need advisor","do i need help","why hire advisor"], question: "How do I know if I need a financial advisor?", answer: "If you are planning for retirement, buying a home, protecting your family, managing investments or running a business, a financial advisor can help by creating an actionable plan and offering ongoing support." }
];

export default faqDatabase;
